[Timescaledb] Improve retention policy procedure
With previous versions, databases with a large number of hypertables would fail applying this policy

```
ERROR:  out of shared memory
HINT:  You might need to increase max_locks_per_transaction.
```

Because by default PostgreSQL is doing the execution of one function in
one single transaction

With the new method, each chunk deletion is commited and there is a lot
message stating for the execution

```
promscale_5801=> call generic_retention(config => '{"drop_after":"1 month"}');
NOTICE:  prom_data.go_memstats_mcache_inuse_bytes
NOTICE:  prom_data.process_cpu_seconds_total
NOTICE:  prom_data.gitaly_supervisor_health_checks_total
NOTICE:  prom_data.go_memstats_gc_sys_bytes
NOTICE:  prom_data.gitaly_repository_optimizerepository_empty_dir_removal_total
NOTICE:  prom_data.gitaly_catfile_processes_total
NOTICE:  prom_data.prometheus_target_interval_length_seconds
NOTICE:  prom_data.etcd_debugging_store_watchers
NOTICE:  prom_data.grafana_plugin_build_info
```